DATA:
  PATH: 'data'
  # data subfolders
  RAW: 'raw'
  PROC: 'processed'
  FINAL: 'final'

SCRAPING:
  NUM_OF_PAGES: 20 # 100 games per page # 1379 pages total
  BATCH_SIZE: 1000 # Recommended < 1200

  # Filenames for scraper to use, no file extensions
  GAME_IDS_FILENAME: 'bgg_game_ids'
  BROWSE_FILENAME: 'bgg_browse_page'
  BATCH_FILENAME: 'bgg_games_batch'

CLASSIFICATIONS:
  - 'category'
  - 'mechanic'